### ISSUE TITLE
Add support of JSON data type

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [CleverCloud/warp10.rs#5]
Hello folks 👋,

Are you interested by the support of JSON data type? I have implemented [here](https://github.com/FlorentinDUBOIS/warp10.rs/commit/628eba8c8b10328db74f8ef1880c5fc7ec6067b8), if you wanna see a possible implementation.

The idea behind is to store as a data point more than a scalar value. It is really useful to group related data without creating new time series, this also help to reduce cardinality of time series. Besides, Warp 10 provide functions to manipulate them, [JSON->](https://www.warp10.io/doc/H_CEIXoy#sigTitle) is one of them.

**Comment by Keruspe** [comment]
Sounds interesting indeed!

I guess we'll have to make stuff fallible to safely implement this

**Comment by FlorentinDUBOIS** [comment]
Of course ! This implementation is here to demonstrate the ability to do it. I will create a pull request with a safe implementation :)
